Run software as another user

diff --git a/0x12-web_stack_debugging_2/0-iamsomeoneelse b/0x12-web_stack_debugging_2/0-iamsomeoneelse
--- a/0x12-web_stack_debugging_2/0-iamsomeoneelse
+++ b/0x12-web_stack_debugging_2/0-iamsomeoneelse
@@ -1,4 +1,10 @@
 #!/usr/bin/env bash
 # Bash script taht accept one argument
 
-echo "$1"
+if [ $# -eq 0 ]; then
+	echo "Error: Provide a username as an argument."
+	exit 1
+fi
+
+username="$1"
+sudo -u "$username" whoami
